platform :ios, '13.0'

target 'Flash Chat' do
  use_frameworks!

  # Pods for Flash Chat
pod 'CLTypingLabel', '~> 0.4.0'

pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'
pod 'FirebaseUI/Storage'

end
